apiVersion: apps/v1
kind: Deployment
metadata:
  name: pb-api
spec:
  replicas: 3
  selector:
    matchLabels:
      name: pb-api
  template:
    metadata:
      labels:
        name: pb-api
    spec:
      containers:
        - name: pb-api
          image: gcr.io/silver-harmony-228021/api:$image_version
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: pb-api-config
              mountPath: /pillsbury/config/api-server
            - name: pb-ethereum-master-key
              mountPath: /pillsbury/config/ethereum-master-key
            - name: pb-ethereum-master-key-pw
              mountPath: /pillsbury/config/ethereum-master-key-pw
            - name: pb-db-config
              mountPath: /pillsbury/config/db
            - name: pb-db-ssl-client-cert
              mountPath: /pillsbury/config/db_certs/client-cert
            - name: pb-db-ssl-client-key
              mountPath: /pillsbury/config/db_certs/client-key
            - name: pb-db-ssl-server-ca
              mountPath: /pillsbury/config/db_certs/server-ca
          env:
            - name: NODE_ENV
              value: production
            - name: API_CONFIG
              value: "/pillsbury/config/api-server/json"
            - name: DB_CONFIG
              value: "/pillsbury/config/db/json"
            - name: DB_NAME
              value: "glaze"
            - name: MASTER_KEY
              value: "/pillsbury/config/ethereum-master-key/json"
            - name: MASTER_KEY_PW
              value: "/pillsbury/config/ethereum-master-key-pw/json"
      volumes:
        - name: pb-api-config
          secret:
            secretName: pb-api-config
            defaultMode: 0400
        - name: pb-ethereum-master-key
          secret:
            secretName: pb-ethereum-master-key
            defaultMode: 0400
        - name: pb-ethereum-master-key-pw
          secret:
            secretName: pb-ethereum-master-key-pw
            defaultMode: 0400
        - name: pb-db-config
          secret:
            secretName: pb-db-config
            defaultMode: 0400
        - name: pb-db-ssl-client-cert
          secret:
            secretName: pb-db-ssl-client-cert
            defaultMode: 0400
        - name: pb-db-ssl-client-key
          secret:
            secretName: pb-db-ssl-client-key
            defaultMode: 0400
        - name: pb-db-ssl-server-ca
          secret:
            secretName: pb-db-ssl-server-ca
            defaultMode: 0400
