apiVersion: apps/v1
kind: Deployment
metadata:
  name: pb-api
spec:
  replicas: 3
  selector:
    matchLabels:
      name: pb-api
  template:
    metadata:
      labels:
        name: pb-api
    spec:
      containers:
        - name: pb-api
          image: gcr.io/silver-harmony-228021/api:$image_version
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: pb-api-config
              mountPath: /pillsbury/config/api-server
            - name: pb-ethereum-node-config
              mountPath: /pillsbury/config/ethereum-node
            - name: pb-ethereum-hub-key
              mountPath: /pillsbury/config/ethereum-hub-key
            - name: pb-ethereum-hub-config
              mountPath: /pillsbury/config/ethereum-hub
            - name: pb-reddit-hub-config
              mountPath: /pillsbury/config/reddit-hub
            - name: pb-db-config
              mountPath: /pillsbury/config/db
            - name: pb-db-ssl-client-cert
              mountPath: /pillsbury/config/db_certs/client-cert
            - name: pb-db-ssl-client-key
              mountPath: /pillsbury/config/db_certs/client-key
            - name: pb-db-ssl-server-ca
              mountPath: /pillsbury/config/db_certs/server-ca
          env:
            - name: NODE_ENV
              value: production
            - name: API_CONFIG
              value: "/pillsbury/config/api-server/json"
            - name: DB_CONFIG
              value: "/pillsbury/config/db/json"
            - name: DB_NAME
              value: "glaze"
            - name: ETHEREUM_NODE_CONFIG
              value: "/pillsbury/config/ethereum-node/json"
            - name: ETHEREUM_HUB_KEY
              value: "/pillsbury/config/ethereum-hub-key/json"
            - name: ETHEREUM_HUB_CONFIG
              value: "/pillsbury/config/ethereum-hub/json"
            - name: REDDIT_HUB_CONFIG
              value: "/pillsbury/config/reddit-hub/json"
            - name: REDDIT_PUPPET_HOST
              value: "pb-reddit-puppet"
            - name: REDDIT_PUPPET_PORT
              value: 8000
      volumes:
        - name: pb-api-config
          secret:
            secretName: pb-api-config
            defaultMode: 0400
        - name: pb-ethereum-node-config
          secret:
            secretName: pb-ethereum-node-config
            defaultMode: 0400
        - name: pb-ethereum-hub-key
          secret:
            secretName: pb-ethereum-hub-key
            defaultMode: 0400
        - name: pb-ethereum-hub-config
          secret:
            secretName: pb-ethereum-hub-config
            defaultMode: 0400
        - name: pb-reddit-hub-config
          secret:
            secretName: pb-reddit-hub-config
            defaultMode: 0400
        - name: pb-db-config
          secret:
            secretName: pb-db-config
            defaultMode: 0400
        - name: pb-db-ssl-client-cert
          secret:
            secretName: pb-db-ssl-client-cert
            defaultMode: 0400
        - name: pb-db-ssl-client-key
          secret:
            secretName: pb-db-ssl-client-key
            defaultMode: 0400
        - name: pb-db-ssl-server-ca
          secret:
            secretName: pb-db-ssl-server-ca
            defaultMode: 0400
