apiVersion: batch/v1
kind: Job
metadata:
  name: pod-reddit-refunder
spec:
  template:
    metadata:
      labels:
        name: pod-reddit-refunder
    spec:
      restartPolicy: Never
      containers:
        - name: pod-reddit-refunder
          image: gcr.io/silver-harmony-228021/reddit-refunder:$image_version
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: pod-reddit-refunder-config
              mountPath: /pod/config/reddit-refunder
            - name: pod-db-config
              mountPath: /pod/config/db
            - name: pod-db-ssl-client-cert
              mountPath: /pod/config/db_certs/client-cert
            - name: pod-db-ssl-client-key
              mountPath: /pod/config/db_certs/client-key
            - name: pod-db-ssl-server-ca
              mountPath: /pod/config/db_certs/server-ca
          env:
            - name: NODE_ENV
              value: production
            - name: REDDIT_REFUNDER_CONFIG
              value: "/pod/config/reddit-refunder/json"
            - name: DB_CONFIG
              value: "/pod/config/db/json"
            - name: DB_NAME
              value: "pod"
      volumes:
        - name: pod-reddit-refunder-config
          secret:
            secretName: pod-reddit-refunder-config
            defaultMode: 0400
        - name: pod-db-config
          secret:
            secretName: pod-db-config
            defaultMode: 0400
        - name: pod-db-ssl-client-cert
          secret:
            secretName: pod-db-ssl-client-cert
            defaultMode: 0400
        - name: pod-db-ssl-client-key
          secret:
            secretName: pod-db-ssl-client-key
            defaultMode: 0400
        - name: pod-db-ssl-server-ca
          secret:
            secretName: pod-db-ssl-server-ca
            defaultMode: 0400
