apiVersion: batch/v1
kind: Job
metadata:
  name: pb-reddit-refunder
spec:
  template:
    metadata:
      labels:
        name: pb-reddit-refunder
    spec:
      restartPolicy: Never
      containers:
        - name: pb-reddit-refunder
          image: gcr.io/silver-harmony-228021/reddit-refunder:$image_version
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: pb-reddit-hub-config
              mountPath: /pillsbury/config/reddit-hub
            - name: pb-db-config
              mountPath: /pillsbury/config/db
            - name: pb-db-ssl-client-cert
              mountPath: /pillsbury/config/db_certs/client-cert
            - name: pb-db-ssl-client-key
              mountPath: /pillsbury/config/db_certs/client-key
            - name: pb-db-ssl-server-ca
              mountPath: /pillsbury/config/db_certs/server-ca
          env:
            - name: NODE_ENV
              value: production
            - name: REDDIT_HUB_CONFIG
              value: "/pillsbury/config/reddit-hub/json"
            - name: DB_CONFIG
              value: "/pillsbury/config/db/json"
            - name: DB_NAME
              value: "glaze"
            - name: REDDIT_PUPPET_HOST
              value: "pb-reddit-puppet"
            - name: REDDIT_PUPPET_PORT
              value: 8000
      volumes:
        - name: pb-reddit-hub-config
          secret:
            secretName: pb-reddit-hub-config
            defaultMode: 0400
        - name: pb-db-config
          secret:
            secretName: pb-db-config
            defaultMode: 0400
        - name: pb-db-ssl-client-cert
          secret:
            secretName: pb-db-ssl-client-cert
            defaultMode: 0400
        - name: pb-db-ssl-client-key
          secret:
            secretName: pb-db-ssl-client-key
            defaultMode: 0400
        - name: pb-db-ssl-server-ca
          secret:
            secretName: pb-db-ssl-server-ca
            defaultMode: 0400
