apiVersion: apps/v1
kind: Deployment
metadata:
  name: pb-ethereum-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pb-ethereum-sender
  template:
    metadata:
      labels:
        name: pb-ethereum-sender
    spec:
      containers:
        - name: pb-ethereum-sender
          image: gcr.io/silver-harmony-228021/ethereum-sender:$image_version
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: pb-ethereum-node-config
              mountPath: /pillsbury/config/ethereum-node
            - name: pb-db-config
              mountPath: /pillsbury/config/db
            - name: pb-db-user-config
              mountPath: /pillsbury/config/db-user
            - name: pb-ethereum-hub-key
              mountPath: /pillsbury/config/ethereum-hub-key
            - name: pb-ethereum-hub-config
              mountPath: /pillsbury/config/ethereum-hub-config
          env:
            - name: NODE_ENV
              value: production
            - name: ETHEREUM_NODE_CONFIG
              value: "/pillsbury/config/ethereum-node/json"
            - name: DB_CONFIG
              value: "/pillsbury/config/db/json"
            - name: DB_USER_CONFIG
              value: "/pillsbury/config/db-user/json"
            - name: DB_NAME
              value: "glaze"
            - name: ETHEREUM_HUB_KEY
              value: "/pillsbury/config/ethereum-hub-key/json"
            - name: ETHEREUM_HUB_CONFIG
              value: "/pillsbury/config/ethereum-hub-config/json"
      volumes:
        - name: pb-ethereum-node-config
          secret:
            secretName: pb-ethereum-node-config
            defaultMode: 0400
        - name: pb-db-config
          secret:
            secretName: pb-db-config
            defaultMode: 0400
        - name: pb-db-user-config
          secret:
            secretName: pb-db-user-config
            defaultMode: 0400
        - name: pb-ethereum-hub-key
          secret:
            secretName: pb-ethereum-hub-key
            defaultMode: 0400
        - name: pb-ethereum-hub-config
          secret:
            secretName: pb-ethereum-hub-config
            defaultMode: 0400
