apiVersion: apps/v1
kind: Deployment
metadata:
  name: pb-reddit-balance-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pb-reddit-balance-monitor
  template:
    metadata:
      labels:
        name: pb-reddit-balance-monitor
    spec:
      containers:
        - name: pb-reddit-balance-monitor
          image: gcr.io/silver-harmony-228021/reddit-balance-monitor:$image_version
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: pb-db-config
              mountPath: /pillsbury/config/db
            - name: pb-db-user-config
              mountPath: /pillsbury/config/db-user
          env:
            - name: NODE_ENV
              value: production
            - name: DB_CONFIG
              value: "/pillsbury/config/db/json"
            - name: DB_USER_CONFIG
              value: "/pillsbury/config/db-user/json"
            - name: DB_NAME
              value: "pillsbury"
            - name: REDDIT_PUPPET_HOST
              value: "pb-reddit-puppet"
            - name: REDDIT_PUPPET_PORT
              value: 8000
      volumes:
        - name: pb-db-config
          secret:
            secretName: pb-db-config
            defaultMode: 0400
        - name: pb-db-user-config
          secret:
            secretName: pb-db-user-config
            defaultMode: 0400
