apiVersion: apps/v1
kind: Deployment
metadata:
  name: pb-ethereum-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pb-ethereum-monitor
  template:
    metadata:
      labels:
        name: pb-ethereum-monitor
    spec:
      containers:
        - name: pb-ethereum-monitor
          image: gcr.io/silver-harmony-228021/ethereum-monitor:$image_version
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: pb-ethereum-node-config
              mountPath: /pillsbury/config/ethereum-node
            - name: pb-contract-config
              mountPath: /pillsbury/config/contracts
            - name: pb-db-config
              mountPath: /pillsbury/config/db
            - name: pb-db-user-config
              mountPath: /pillsbury/config/db-user
          env:
            - name: NODE_ENV
              value: production
            - name: ETHEREUM_NODE_CONFIG
              value: "/pillsbury/config/ethereum-node/json"
            - name: CONTRACT_CONFIG
              value: "/pillsbury/config/contracts/json"
            - name: DB_CONFIG
              value: "/pillsbury/config/db/json"
            - name: DB_USER_CONFIG
              value: "/pillsbury/config/db-user/json"
            - name: DB_NAME
              value: "glaze"
      volumes:
        - name: pb-ethereum-node-config
          secret:
            secretName: pb-ethereum-node-config
            defaultMode: 0400
        - name: pb-contract-config
          secret:
            secretName: pb-contract-config
            defaultMode: 0400
        - name: pb-db-config
          secret:
            secretName: pb-db-config
            defaultMode: 0400
        - name: pb-db-user-config
          secret:
            secretName: pb-db-user-config
            defaultMode: 0400
