apiVersion: apps/v1
kind: Deployment
metadata:
  name: pb-reddit-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pb-reddit-monitor
  template:
    metadata:
      labels:
        name: pb-reddit-monitor
    spec:
      containers:
        - name: pb-reddit-monitor
          image: gcr.io/silver-harmony-228021/reddit-monitor:$image_version
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: pb-reddit-monitor-config
              mountPath: /pillsbury/config/reddit-monitor
            - name: pb-db-config
              mountPath: /pillsbury/config/db
            - name: pb-db-ssl-client-cert
              mountPath: /pillsbury/config/db_certs/client-cert
            - name: pb-db-ssl-client-key
              mountPath: /pillsbury/config/db_certs/client-key
            - name: pb-db-ssl-server-ca
              mountPath: /pillsbury/config/db_certs/server-ca
          env:
            - name: NODE_ENV
              value: production
            - name: REDDIT_MONITOR_CONFIG
              value: "/pillsbury/config/reddit-monitor/json"
            - name: DB_CONFIG
              value: "/pillsbury/config/db/json"
            - name: DB_NAME
              value: "pillsbury"
      volumes:
        - name: pb-reddit-monitor-config
          secret:
            secretName: pb-reddit-monitor-config
            defaultMode: 0400
        - name: pb-db-config
          secret:
            secretName: pb-db-config
            defaultMode: 0400
        - name: pb-db-ssl-client-cert
          secret:
            secretName: pb-db-ssl-client-cert
            defaultMode: 0400
        - name: pb-db-ssl-client-key
          secret:
            secretName: pb-db-ssl-client-key
            defaultMode: 0400
        - name: pb-db-ssl-server-ca
          secret:
            secretName: pb-db-ssl-server-ca
            defaultMode: 0400
