apiVersion: batch/v1
kind: Job
metadata:
  name: pb-glaze-db-updater
spec:
  template:
    metadata:
      labels:
        name: pb-glaze-db-updater
    spec:
      restartPolicy: Never
      containers:
        - name: pb-glaze-db-updater
          image: gcr.io/silver-harmony-228021/glaze-db-updater:$image_version
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: pb-db-config
              mountPath: /pillsbury/config/db
            - name: pb-db-ssl-client-cert
              mountPath: /pillsbury/config/db_certs/client-cert
            - name: pb-db-ssl-client-key
              mountPath: /pillsbury/config/db_certs/client-key
            - name: pb-db-ssl-server-ca
              mountPath: /pillsbury/config/db_certs/server-ca
          env:
            - name: NODE_ENV
              value: production
            - name: DB_CONFIG
              value: "/pillsbury/config/db/json"
      volumes:
        - name: pb-db-config
          secret:
            secretName: pb-db-config
            defaultMode: 0400
        - name: pb-db-ssl-client-cert
          secret:
            secretName: pb-db-ssl-client-cert
            defaultMode: 0400
        - name: pb-db-ssl-client-key
          secret:
            secretName: pb-db-ssl-client-key
            defaultMode: 0400
        - name: pb-db-ssl-server-ca
          secret:
            secretName: pb-db-ssl-server-ca
            defaultMode: 0400
