apiVersion: batch/v1
kind: Job
metadata:
  name: pb-glaze-db-updater
spec:
  template:
    metadata:
      labels:
        name: pb-glaze-db-updater
    spec:
      restartPolicy: Never
      containers:
        - name: pb-glaze-db-updater
          image: gcr.io/silver-harmony-228021/glaze-db-updater:$image_version
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: pb-db-config
              mountPath: /pillsbury/config/db
            - name: pb-db-user-config
              mountPath: /pillsbury/config/db-user
          env:
            - name: NODE_ENV
              value: production
            - name: DB_CONFIG
              value: "/pillsbury/config/db/json"
      volumes:
        - name: pb-db-config
          secret:
            secretName: pb-db-config
            defaultMode: 0400
        - name: pb-db-user-config
          secret:
            secretName: pb-db-user-config
            defaultMode: 0400
